#### 1.Загрузите numpy пакет под именем `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Выведите на печать версию numpy(★☆☆)

In [2]:
print(np.__version__)

1.22.2


#### 3. Создайте вектор из 10 нулей (★☆☆)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Как найти размер (в байтах) всего массива  (★☆☆)

In [173]:
arr = np.zeros(10)
arr.nbytes

80

#### 5. Как получить подсказку по функции numpy? (★☆☆)

In [ ]:
(Shift + Tab)

#### 6. Создайте нулевой вектор размера 10, где пятое значение будет равно 1(★☆☆)

In [8]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Создайте вектор размера 10 и заполните случайными значениями от 10 до 49 (★☆☆)

In [9]:
arr = np.random.randint(10,49, 10)
print(arr)

[12 20 38 25 19 42 35 48 35 19]


#### 8. Сделайте отражение вектора (первый элемент — последний, а последний — первый) (★☆☆)

In [12]:
arr[::-1]

array([19, 35, 48, 35, 42, 19, 25, 38, 20, 12])

#### 9. Создайте 3x3 матрицу со значениями от 0 до 8 (по очереди) (★☆☆)

In [15]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Найдите все индексы ненулевых элементов в массиве [1,2,0,0,4,0] (★☆☆)

In [141]:
arr = np.array([1,2,0,0,4,0])

np.where(arr != 0)[0] # или
np.nonzero(arr)

array([0, 1, 4], dtype=int64)

#### 11. Создайте единичную матрицу размера 3х3 (★☆☆)

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Создайте массив 3x3x3 со случайными значениями (★☆☆)

In [20]:
np.random.randint(100, size=(3,3,3))

array([[[67,  4, 50],
        [95, 19, 53],
        [34, 44, 62]],

       [[33, 99, 83],
        [56, 77, 21],
        [83, 78, 67]],

       [[17,  2, 92],
        [47, 13, 62],
        [33, 63, 29]]])

#### 13. Создайте массив размера 10x10 со случайными значениями и найдите минимальные и максимальные значения (по всему массиву) (★☆☆)

In [31]:
arr = np.random.randint(100, size=(10,10))
print(arr)

print(arr[np.unravel_index(arr.argmax(), arr.shape)])
print(arr[np.unravel_index(arr.argmin(), arr.shape)])

[[ 8 39 92  0 41 39 92 22 67 15]
 [53 21 70  1 55 99 92 56 70 59]
 [39 10 53 13 12 38 71 84 82 67]
 [ 1 89 33  2 60 65 95 56 56 33]
 [54  1 92 45 24 58 39 10 54  3]
 [61 74 53 88 74 46 93 85 14 11]
 [ 4 55 88 92 22 49 21 55 53 47]
 [74 42 43 14 70 73 31 24 76 90]
 [94 23 73  3 38 16 70 22  3 27]
 [86 11 63 64  0 56 94 53 92 40]]
99
0


#### 14. Создайте случайный вектор размера 30 и найдите среднее значение (★☆☆)

In [41]:
arr = np.random.randint(100, size=(30))
print(arr)
print(np.average(arr))

[50 53 60 89 15  3 64 73 22 64 94 76 83 48  2 69 43 24 70 57 38 83 60 71
 65 69 20 42 67 54]
54.266666666666666


#### 15. создайте матрицу 5x5 со значениями 0,1,2,3,4 на диагонале (★☆☆)

In [47]:
np.diag(np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

#### 16. Как посчитать ((A+B)*(-A/2)) без копирования? (операции обычные) (★★☆)

In [144]:
A = np.random.randint(10, size=(2,2))
B = np.random.randint(10, size=(2,2))
print(A)
print(B)
(A+B) * (-A / 2)

[[5 2]
 [6 3]]
[[5 4]
 [2 0]]


array([[-25. ,  -6. ],
       [-24. ,  -4.5]])

#### 17. Создайте вектор размера 10 в равном промежутке от 0 до 1 (включая границы)  (★★☆)

In [49]:
np.linspace(0, 1, 10) # endpoint=True по умолчанию

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### 18. Создайте случайный вектор размера 10 и отсортируйте его (★★☆)

In [52]:
arr = np.random.randint(30, size=10)
print(arr)
print(np.sort(arr))

[25 23  5 10  1 20  8 10  7 13]
[ 1  5  7  8 10 10 13 20 23 25]


#### 19. Создайте два случайных массива и проверьте являются ли они одного размера (★★☆)

In [134]:
arr1 = np.random.randint(30, size = (5,5))
arr2 = np.random.randint(30, size = (5,4))
print(arr1)
print(arr2)
print(arr1.shape == arr2.shape)

[[29  6 13 28 19]
 [21  5 11  8 13]
 [ 5 29 29 21 10]
 [11 15 15 17  6]
 [ 5 14 16 14 16]]
[[20 10  0 10]
 [20 28 10 21]
 [ 5  5 23 23]
 [ 0 20 20  9]
 [23 15 18 26]]
False


#### 20. Создайте случайную матрицу 10х10 и замените в ней все максимальные элементы на 100, а минимальные на 0 (по двум осям отдельно) (★★☆)

In [170]:
arr1 = np.random.randint(30, size = (10,10))
print(arr1)

def changeElem(numAxis, arr1):
    max_ind = np.argmax(arr1, axis=numAxis)
    min_ind = np.argmin(arr1, axis=numAxis) # находим индексы максимальных и минимальных

    row_ind = np.arange(arr1.shape[0])
    multiMax_ind = np.array([row_ind, max_ind]) 
    multiMin_ind = np.array([row_ind, min_ind])

    linearMax_ind = np.ravel_multi_index(multiMax_ind, arr1.shape)
    linearMin_ind = np.ravel_multi_index(multiMin_ind, arr1.shape)

    arr1.reshape((-1))[linearMax_ind] = 100
    arr1.reshape((-1))[linearMin_ind] = 0
    return arr1

changeElem(1, arr1)
changeElem(0, arr1)

print(arr1)

[[28 16 15 26 14 13  7 21  8  0]
 [ 4 25  5 25 27 19 16 27 13 19]
 [ 4 20  1 17 26 15  7 24 14 21]
 [29  6 23  6 21  1  7 19 16 12]
 [26  2  0  1 18 13  8  7 12 13]
 [10  4  9 10 13 22 18 16 28  0]
 [ 1  5 17 15 11 25  0 15  3 11]
 [23 22 12 17 22 28  1 12 29 19]
 [17 23 10  0 19  3 21 21  8 18]
 [26 25 15  4 21  6 13 11 21 29]]
[[0 1 2 3 4 5 6 7 8 9]
 [0 4 4 0 0 8 5 8 1 9]]
[[0 1 2 3 4 5 6 7 8 9]
 [0 8 3 0 1 6 8 1 5 9]]
[[100   0  15  26  14  13   7  21   8   0]
 [  0  25   5  25   0  19  16  27 100  19]
 [  4  20   0 100 100  15   7  24  14  21]
 [100   6  23   6  21   0   7  19   0  12]
 [100 100   0   1  18  13   0   7  12  13]
 [ 10   4   9   0  13  22 100  16 100   0]
 [  1   5  17  15  11 100   0  15 100  11]
 [ 23 100  12  17   0  28   0  12 100  19]
 [ 17 100  10   0  19 100   0  21   8  18]
 [  0  25  15   0  21   6  13  11  21 100]]


#### 21. Создайте массив, который будет представлять позицию (x,y) и цвет (r,g,b) пикселя изображения (★★☆) A[x,y]= (r,g,b)

In [171]:
picture = np.array(np.random.randint(0,255, (5,5,3)))
print(picture)
print(picture[2,3])

[[[ 46 189 167]
  [ 42 233  44]
  [152 248 192]
  [ 81  99  84]
  [133 253 156]]

 [[108  84 167]
  [ 11 110 187]
  [225 186  70]
  [112  13  14]
  [246  23  96]]

 [[221 124 237]
  [202  13 213]
  [ 53  55   4]
  [243  57 146]
  [126 122   3]]

 [[190 103 228]
  [211 115 212]
  [ 72  31  23]
  [  3  40 190]
  [230 119  14]]

 [[ 22  40  53]
  [125 233 236]
  [ 99  11 126]
  [ 51 155 173]
  [ 94  71 153]]]
[243  57 146]


#### 22. Прочитайте следующий файл в numpy.ndarray? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [133]:
arr = np.genfromtxt("matrix.txt", delimiter=",")
print(arr)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 23. У случайного вектора размера 100 увеличьте каждый второй элемент на 1? (★★★)

In [129]:
arr = np.random.randint(30, size = 100)
print(arr)
arr[::2] = arr[::2] + 1
print(arr)

[22 21  7  0 19  1  6  5 24 20  2  1  9 12 17  5 22 24 12  2 11 26 15  7
 24 24 18 20  7 10 25 25 12  1 17  4 14 18 22 12 21  3 24  3  6  4  0 28
 10 21 15  8 12  4  8 28 10  9  2 26 23 29 22 29 26  9 14 11 17  0 13 16
 21  2 20 18 15  7 22 17  4 25 25  3 11 12 21 11 28 14  5 15 29 22 28  7
  5 19 12 28]
[23 21  8  0 20  1  7  5 25 20  3  1 10 12 18  5 23 24 13  2 12 26 16  7
 25 24 19 20  8 10 26 25 13  1 18  4 15 18 23 12 22  3 25  3  7  4  1 28
 11 21 16  8 13  4  9 28 11  9  3 26 24 29 23 29 27  9 15 11 18  0 14 16
 22  2 21 18 16  7 23 17  5 25 26  3 12 12 22 11 29 14  6 15 30 22 29  7
  6 19 13 28]


#### 24. Для случайного 4х мерного массива размера 100х100х100х100 получите сумму элементов (попарную для двух последних осей)? (★★★)

In [119]:
arr = np.random.randint(30, size = (100,100,100,100))
print(arr[98, 98, 98, :])
print(arr[99, 99, 99, :])
print(arr[98, 98, 98, :] + arr[99, 99, 99, :])

[12 29  0 12 28  8  4  1  0 14 23  1 28 12 12  8  8 22  5 13 10 24  6  7
 23 29 28  3 15 25 11  5 19  9 20 22 15 20  7 13  2 28 29 16  5  9 21  9
  8 25 18 17 27 21  4 23  8  7 21 19 28 17  9  9 24 10 19  2  1  0 22  8
  2 21  7 25  2 10 19 10 11 21 14 25 22  8 20 17 12  7 14  1 20 14 21 22
  7  9  1 28]
[15 17 10  6 29 27  0 10 23 22  1  5 27 23 21  8 15  9  7  1  4 20 10 14
  3 17  1 29 26  3 17 25 10 17 15 14  3  4 21 28  9 20  3 26 26 19 17  0
  7 29 16 27 27 11  5 29 25 12 10  9  4 15 21 16 13 12 24 21 15  9 28 15
 14 26 11 11  2 20 15  6 23 13 18 24 17 14  1 12 21  4 18 21 22 24 26 22
 17 17 25  4]
[27 46 10 18 57 35  4 11 23 36 24  6 55 35 33 16 23 31 12 14 14 44 16 21
 26 46 29 32 41 28 28 30 29 26 35 36 18 24 28 41 11 48 32 42 31 28 38  9
 15 54 34 44 54 32  9 52 33 19 31 28 32 32 30 25 37 22 43 23 16  9 50 23
 16 47 18 36  4 30 34 16 34 34 32 49 39 22 21 29 33 11 32 22 42 38 47 44
 24 26 26 32]


#### 25. В случайном массиве 10х10 поменяйте две строки местами? (★★★)

In [114]:
arr1 = np.random.randint(30, size = (10,10))
print(arr1)
# меняем 1 и 6 строку местами
arr1[(5, 0), :] = arr1[(0, 5), :]
print(arr1)

[[28 21  1  5 16  7  0 10 22 15]
 [17 28 15 17 11 10 19  5 12 26]
 [21  6 28 15 28  1 24 28 16 16]
 [ 9 27 22  6 19  3 27 17  9 24]
 [ 0 21 16 25 27 29  5 16 24 25]
 [10  1 12 22  9 20 21  9 25 19]
 [19 27  6 12 27  6 19  1 12 10]
 [17 28 28 23 13 16 15  7 25 15]
 [ 0 10 24 24 26 16 19 25 16 12]
 [11 12  6  3 20  9  0 12  6 25]]
[[10  1 12 22  9 20 21  9 25 19]
 [17 28 15 17 11 10 19  5 12 26]
 [21  6 28 15 28  1 24 28 16 16]
 [ 9 27 22  6 19  3 27 17  9 24]
 [ 0 21 16 25 27 29  5 16 24 25]
 [28 21  1  5 16  7  0 10 22 15]
 [19 27  6 12 27  6 19  1 12 10]
 [17 28 28 23 13 16 15  7 25 15]
 [ 0 10 24 24 26 16 19 25 16 12]
 [11 12  6  3 20  9  0 12  6 25]]


#### 26. Посчитайте ранг случайной матрицы 3х3? (★★★)

In [69]:
arr = np.random.randint(0, 2, size = (3,3))
A = np.asmatrix(arr)
rank = np.linalg.matrix_rank(A)
print(A)
print(rank)

[[0 0 1]
 [0 0 0]
 [0 1 1]]
2
