In [2]:
import numpy as np # библиотека векторных вычислений (C)
print(np.__version__)

import scipy as sc # научные вычислений (С++, Fortran)
print(sc.__version__)

1.21.2
1.7.3


# Циклы?

In [4]:
Py_list = list(range(10000))
Np_list = np.arange(10000)


array([   0,    1,    2, ..., 9997, 9998, 9999])

In [5]:
%%timeit

for i in Py_list: # эквивалентно [i * i for i in Py_list]
    i*i

195 µs ± 5.78 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [6]:
%%timeit
Np_list * Np_list

3.09 µs ± 126 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## А если двумерный?

In [7]:
col, row = 10, 10
ar = [[i for j in range(col)] for i in range(row)]
ar
# Тоже самое
# ar= [[0] * row] * col
# for i in range(row):
#     for j in range(col):
#         ar[i][j] = j

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
 [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
 [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
 [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
 [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
 [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
 [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
 [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]]

In [8]:
%%timeit
for i in range(row):
    for j in range(col):
        ar[i][j]*= 2

The slowest run took 4.03 times longer than the fastest. This could mean that an intermediate result is being cached.
113 µs ± 45.7 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [9]:
%%timeit
Np_list2D = np.asarray(ar)
Np_list2D = Np_list2D*2

220 µs ± 2.38 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# Как создать массив?

In [10]:
Np_list = np.array([1,2,3]) #создаст копию списка
Np_list

array([1, 2, 3])

In [18]:
Np_list = np.array([1,2,3])
type(Np_list[2])

numpy.float64

# Типы dtype
![jupyter](./МАПЗ/Рисунок1.jpg)

https://numpy.org/doc/stable/reference/arrays.dtypes.html

In [26]:
Np_list = np.array([[1,2,3],
                   [1,2,3],
                   [1,2,3],
                   [1,2,3]])
Np_list

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [27]:
Np_list.shape # размер массива

(4, 3)

In [28]:
Np_list.ndim # количество размерностей

2

In [29]:
print(Np_list.dtype) # правильный вариант
print(type(Np_list)) # неправильный вариант
print(type(Np_list[0][0])) # но зачем?)

int32
<class 'numpy.ndarray'>
<class 'numpy.int32'>


In [33]:
Np_list.astype(int)
Np_list.dtype

dtype('float64')

### Strides

In [34]:
Np_list

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [35]:
Np_list.dtype

dtype('float64')

In [36]:
Np_list.dtype.itemsize #размер объекта внутри массива

8

In [37]:
Np_list.shape

(4, 3)

In [38]:
Np_list.strides # (переход на следующую строку, переход на следующий элемент)

(24, 8)

In [42]:
Np_list = Np_list.reshape(3,4) #изменяем размер
Np_list.shape


(3, 4)

In [43]:
Np_list.strides #проверяем

(32, 8)

In [55]:
Np_list = Np_list.reshape(4,3) # -1 заменяет необходимый аргумент в кол-ве 
Np_list.shape
Np_list

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

## Ещё изменение массивов

In [61]:
Np_list = np.array([[1,2,3],
                   [1,2,3],
                   [1,2,3]])
Np_list

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [57]:
temp = Np_list.flatten() # копия
Np_list[0,0]= -10
print(Np_list)
print(temp)

[[-10   2   3]
 [  1   2   3]
 [  1   2   3]]
[1 2 3 1 2 3 1 2 3]


In [58]:
temp = Np_list.ravel() # не возвращает копию
Np_list[0,0]= -20
print(Np_list)
print(temp)

[[-20   2   3]
 [  1   2   3]
 [  1   2   3]]
[-20   2   3   1   2   3   1   2   3]


In [63]:
temp = Np_list.T # НЕ СОЗДАЁТ КОПИЮ!
print(temp)
temp[0][1] = 5
print(Np_list)
print(temp)

[[1 5 1]
 [2 2 2]
 [3 3 3]]
[[1 2 3]
 [5 2 3]
 [1 2 3]]
[[1 5 1]
 [2 2 2]
 [3 3 3]]


## Особые массивы

In [71]:
np.zeros(shape = (10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [72]:
np.zeros_like(Np_list)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [75]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [76]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [81]:
np.arange(0,10,0.5) #дробный шаг!

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [85]:
np.linspace(1,10,5,endpoint=True)

array([1. , 2.8, 4.6, 6.4, 8.2])

## Оптимизация массивов по памяти

In [88]:
arr1 = np.array([0,1,2,3])
arr2 = np.array(arr1) # копия данных
arr3 = np.asarray(arr1) # те же данные

arr2, arr3

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [89]:
arr1[2] = 10
arr2, arr3

(array([0, 1, 2, 3]), array([ 0,  1, 10,  3]))

## Унарные и бинарные операции

In [188]:
arr1 = np.array([0,1,2,3])

In [189]:
arr1 + 2 # np.add(arr1,2)

array([2, 3, 4, 5])

In [190]:
arr1 * 2 # np.multiply(arr1,2)

array([0, 2, 4, 6])

In [191]:
arr1 ** 2 # np.pow(arr1,2)

array([0, 1, 4, 9], dtype=int32)

In [99]:
np.exp(arr1)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [101]:
np.log10(arr1+1)

array([0.       , 1.       , 1.5849625, 2.       ])

In [104]:
arr1>1

array([2, 3])

## Функции над массивами

In [105]:
arr1 = np.array([0,1,2,3])
arr1

array([0, 1, 2, 3])

In [106]:
arr1.max(), arr1.min(), arr1.argmin(), np.median(arr1), np.prod(arr1) # min(), max(), sum() только для одномерного!

(3, 0, 0, 1.5, 0)

## Представление массивов
![jupyter](./МАПЗ/Рисунок2.jpg)

Axis0 = |   
Axis1 = —  
Axis2 = / 


https://python-scripts.com/numpy

In [111]:
arr1 = np.array([[1,2,3],
                   [1,2,3],
                   [1,2,10]])
arr1

array([[ 1,  2,  3],
       [ 1,  2,  3],
       [ 1,  2, 10]])

In [114]:
arr1.max(axis=1)

array([ 3,  3, 10])

In [115]:
arr1.argmax() # индекс 8????

8

In [118]:
np.unravel_index(arr1.argmax(), arr1.shape)


(2, 2)

## Бинарные операции

In [192]:
arr1 = np.array([[1,2,3],
                   [1,2,3],
                   [1,2,10]],dtype =int)

arr2 = np.random.randint(0,10, size=arr1.shape)
arr2 = arr2.astype(float)
print(arr1)
print()
print(arr2)

[[ 1  2  3]
 [ 1  2  3]
 [ 1  2 10]]

[[0. 7. 0.]
 [7. 9. 2.]
 [5. 6. 9.]]


In [193]:
arr1 * arr2

array([[ 0., 14.,  0.],
       [ 7., 18.,  6.],
       [ 5., 12., 90.]])

In [127]:
arr1 + arr2

array([[ 8., 10., 11.],
       [ 6.,  2.,  8.],
       [ 6.,  8., 14.]])

In [128]:
arr1 < arr2

array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [129]:
np.isclose(arr1,arr2) # позволяет сравнивать int и float (Shift+tab)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

## Правила бинарных операций над масивами.

1) Пусть a.shape = $(a_1,a_2,a_3...a_n)$, а b.shape = $(b_1,b_2,b_3...b_n)$, тогда бинарную операцию можно если верен любой из следующих условий:
- $a_i = b_i$
- $a_i = 1$
- $b_i = 1$

2) Если размерность не совпадает, то к массиву меньшего размера добавляется фиктивные оси в начало


In [134]:
arr1 = np.arange(15).reshape(5,3)
print(arr1)
print()
arr2 = np.arange(5).reshape(5,1)
print(arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

[[0]
 [1]
 [2]
 [3]
 [4]]


In [135]:
arr1 * arr2

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [12, 14, 16],
       [27, 30, 33],
       [48, 52, 56]])

In [136]:
arr2 = np.repeat(arr2, 3, axis=1)
arr2

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [137]:
arr1 * arr2

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [12, 14, 16],
       [27, 30, 33],
       [48, 52, 56]])

## Матричные операции

In [138]:
A = np.arange(5,9).reshape(-1,2)
B = np.asarray([[1,2],[2,1]])
print(A)
print(B)

[[5 6]
 [7 8]]
[[1 2]
 [2 1]]


In [139]:
A*B

array([[ 5, 12],
       [14,  8]])

In [140]:
np.matmul(A,B)

array([[17, 16],
       [23, 22]])

In [141]:
np.asmatrix(A)

# https://docs.scipy.org/doc/scipy/reference/linalg.html <— Решение матричных задач

matrix([[5, 6],
        [7, 8]])

## Индексация

In [142]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
arr[1:5:]

array([1, 2, 3, 4])

In [144]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [151]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Маски

In [152]:
arr = np.random.randint(1,100,20)
arr

array([45,  7, 60, 13, 49, 87, 68, 30, 91, 30, 65, 71, 53, 85, 22, 74, 34,
       91, 79, 60])

In [153]:
arr<20

array([False,  True, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [154]:
arr[arr<20]

array([ 7, 13])

## Индексация многомерные массивы

In [155]:
arr = np.random.randint(1,20,[5,5])
arr

array([[16,  7, 16,  2,  4],
       [13, 13,  4, 14, 14],
       [17,  8, 16,  4, 13],
       [12,  5, 14, 15, 16],
       [ 7, 12, 15,  3, 12]])

In [156]:
%%timeit
arr[0][0] # плохо

106 ns ± 2.38 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [157]:
%%timeit
arr[0,0]  # хорошо

52.9 ns ± 1.78 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [158]:
#вывод строки
print(arr[2])
print(arr[2,::])

[17  8 16  4 13]
[17  8 16  4 13]


In [161]:
#вывод столбца
print(arr[:,2])

[16  4 16 14 15]


In [164]:
print(arr)
np.where(arr<20) # индекс строк / индекс столбцов

[[16  7 16  2  4]
 [13 13  4 14 14]
 [17  8 16  4 13]
 [12  5 14 15 16]
 [ 7 12 15  3 12]]


(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
        4, 4, 4], dtype=int64),
 array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
        2, 3, 4], dtype=int64))

In [167]:
arr[[1,2,3]] #получить 

array([[13, 13,  4, 14, 14],
       [17,  8, 16,  4, 13],
       [12,  5, 14, 15, 16]])

## Объединение массивов, сортировка, полезные фишки

In [170]:
arr1 = np.random.randint(1,20,(5,5))
arr2 = np.random.randint(1,20,(5,5))
print(arr1)
print()
print(arr2)

[[11 12 14  3 11]
 [ 9 17  9 15  1]
 [ 3  8 18 13  9]
 [ 4  1 18  6  6]
 [12  4 15  5 11]]

[[ 3 19 11 10  4]
 [13 11 11 10 15]
 [14  6 16 13 18]
 [ 8  6  1  8 11]
 [ 2  3  5  2 14]]


In [173]:
np.concatenate((arr1,arr2),axis=1)

array([[11, 12, 14,  3, 11,  3, 19, 11, 10,  4],
       [ 9, 17,  9, 15,  1, 13, 11, 11, 10, 15],
       [ 3,  8, 18, 13,  9, 14,  6, 16, 13, 18],
       [ 4,  1, 18,  6,  6,  8,  6,  1,  8, 11],
       [12,  4, 15,  5, 11,  2,  3,  5,  2, 14]])

In [174]:
np.concatenate((arr1,arr2),axis=0)

array([[11, 12, 14,  3, 11],
       [ 9, 17,  9, 15,  1],
       [ 3,  8, 18, 13,  9],
       [ 4,  1, 18,  6,  6],
       [12,  4, 15,  5, 11],
       [ 3, 19, 11, 10,  4],
       [13, 11, 11, 10, 15],
       [14,  6, 16, 13, 18],
       [ 8,  6,  1,  8, 11],
       [ 2,  3,  5,  2, 14]])

In [176]:
arr1

array([[11, 12, 14,  3, 11],
       [ 9, 17,  9, 15,  1],
       [ 3,  8, 18, 13,  9],
       [ 4,  1, 18,  6,  6],
       [12,  4, 15,  5, 11]])

In [186]:
np.sort(arr1, axis=0) #копия объекта


array([[ 3,  1,  9,  3,  1],
       [ 4,  4, 14,  5,  6],
       [ 9,  8, 15,  6,  9],
       [11, 12, 18, 13, 11],
       [12, 17, 18, 15, 11]])

In [187]:
arr1.sort(axis=0) # inplace сортировка

In [185]:
np.unique(arr1) # уникальные элементы

array([ 1,  3,  4,  5,  6,  8,  9, 11, 12, 13, 14, 15, 17, 18])

In [194]:
np.nan

nan